### ISSUE TITLE
Please move from native to Skylark rules for external git/http repositories

### ISSUE THREAD

**Issue by aehlig** [bazelbuild/rules_groovy#15]
Bazel is planning to move away from native rules for external repositories to Skylark rules, mainly because bundling every version control system in bazel does not scale. As part of this effort, we plan to submit https://bazel-review.googlesource.com/c/bazel/+/55932 soon, which will cause bazel by default to insist that the skylark versions the git and http rules for external repositories be used. This can be disabled by a flag for at least the next 6 months, but we still would appreciate if you could adopt your repository to use the Skylark versions of those rules soon.

A test run of downstream projects with that flag flip in bazel enabled can be found at https://buildkite.com/bazel/bazel-with-downstream-projects-bazel/builds/286

For more background, see
- the original announcement https://groups.google.com/d/topic/bazel-discuss/dO2MHQLwJF0/discussion
- and the documentation of the incompatible changes https://docs.bazel.build/versions/master/skylark/backward-compatibility.html#remove-native-git-repository

Thanks.

**Comment by ekuefler** [comment]
Hi Klaus - could you give me access to the project on buildkite? Also, is there a way for me to check on the current version of Bazel whether I've done the fix correctly? When I run `bazel build --incompatible_remove_native_http_archive ...` locally in this repo I don't see any errors.

**Comment by aehlig** [comment]
For buildkite access, you would have to ask @buchgr or @philwo. But if running `bazel build --all_incompatible_changes ...` works, things are fine. Thanks.

**Comment by mhlopko** [comment]
Hi all, this flag is flipped now at bazel@HEAD and will be the default behavior of Bazel 0.20. I'll disable this project on our downstream pipeline (https://buildkite.com/bazel/bazel-with-downstream-projects-bazel/builds/531#4f97d76d-51b2-414e-8f12-313de6ac1e14). Please fix quickly and create an issue at bazelbuild/continuous-integration to reenable. Keep in mind that we are not catching unintentional breakages of this project in bazel@HEAD.

**Comment by meteorcloudy** [comment]
@ekuefler 
I don't think with 0.18.0 `bazel build --incompatible_remove_native_http_archive ...` still works, see
```
pcloudy@ ~/workspace/rules_groovy master 
$ /usr/bin/bazel version
Starting local Bazel server and connecting to it...
Build label: 0.18.0
Build target: bazel-out/k8-opt/bin/src/main/java/com/google/devtools/build/lib/bazel/BazelServer_deploy.jar
Build time: Mon Oct 15 08:33:18 2018 (1539592398)
Build timestamp: 1539592398
Build timestamp as int: 1539592398
pcloudy@ ~/workspace/rules_groovy master 
$ /usr/bin/bazel build --incompatible_remove_native_http_archive ...
ERROR: /usr/local/google/home/pcloudy/workspace/rules_groovy/groovy/groovy.bzl:414:3: no such package '@groovy_sdk_artifact//': The native new_http_archive rule is deprecated. load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive") for a drop-in replacement.
Use --incompatible_remove_native_http_archive=false to temporarily continue using the native rule. and referenced by '//external:groovy'
ERROR: Analysis of target '//example/src/main/groovy/app:GroovyApp' failed; build aborted: Analysis failed
INFO: Elapsed time: 2.195s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (10 packages loaded)
```

You'll have to fix
https://github.com/bazelbuild/rules_groovy/blob/b20234c9cf499f2243a1b461b409832faf7d2681/groovy/groovy.bzl#L393
with `load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive")`

**Comment by ekuefler** [comment]
Not sure why I was unable to repro before, but it did now and the fix should solve it.
