### ISSUE TITLE
Get all tests passing with --all_incompatible_changes under Bazel 0.20

### ISSUE THREAD

**Issue by greggdonovan** [bazelbuild/rules_groovy#25]
rules_groovy has a number of incompatible changes as of 0.20.0. It is a dependency for `rules_docker`, which we use.

**Comment by asv** [comment]
Can publish a release? The 0.0.3 release does not work on current versions of Bazel.

**Comment by greggdonovan** [comment]
@asv We just use the HEAD commit.

**Comment by ekuefler** [comment]
I've cut an 0.0.4 release and updated the README.

**Comment by asv** [comment]
@ekuefler thanks.
