### ISSUE TITLE
Groovy SDK and Spock core library versions are outdated

### ISSUE THREAD

**Issue by bmuschko** [bazelbuild/rules_groovy#38]
At the moment the following versions are used:

* Groovy SDK [version 2.4.4](https://github.com/bazelbuild/rules_groovy/blob/master/groovy/groovy.bzl#L402)
* Spock core [version 0.7-groovy-2.0](https://github.com/bazelbuild/rules_groovy/blob/master/groovy/groovy.bzl#L444)

It would be a good idea to move to a newer version by default. I'd be happy to send a pull request. Let me know what you think.

**Comment by ekuefler** [comment]
Updating the defaults sounds good - would be great if you wanted to send a PR for it!

**Comment by bmuschko** [comment]
Sure, I am planning to work on a PR in the next couple of days.

**Comment by bmuschko** [comment]
Sent PR https://github.com/bazelbuild/rules_groovy/pull/42

**Comment by bmuschko** [comment]
This is somewhat of a moving target. For example, Groovy 2.5.9 has been released in the meantime. Do you have ideas around maintaining newer versions going forward or are you relying on the community to provide PRs for this?

**Comment by bmuschko** [comment]
For now I am going to close this issue as the original request has been fixed. Let me know what you think though.

**Comment by ekuefler** [comment]
Yeah, I don't know of a better option here than just sending PRs when a new version comes out. Note that these are just the defaults, so updates here shouldn't block anyone since it's always possible to specify a newer version manually.

**Comment by bmuschko** [comment]
@ekuefler Will do. Do you have example code that shows how to reconfigure the default version of a library? A code snippet here should do as well.
